import { Content } from '@/types/content';

// TODO: [백엔드 연동] 더미데이터를 /api/contents 실제 호출로 교체
export const DUMMY_CONTENTS: Content[] = [
  {
    id: '1',
    slug: 'mbti-basic',
    category: 'mbti',
    title: 'MBTI 기본 유형 해석',
    // PRD 6-1.1: 감정 공감 + 궁금증 유발 구조로 교체
    description: '나조차 몰랐던 내 성격의 뿌리를 꺼내드립니다',
    price: 9900,
    badge: 'popular',
    thumbnailEmoji: '🧠',
    gradientFrom: '#4A3B5C',
    gradientTo: '#F5D7E8',
    is_active: true,
  },
  {
    id: '2',
    slug: 'saju-deep',
    category: 'saju',
    title: '심층 사주 분석',
    description: '언제 기회가 오는지, 어떤 사람이 맞는지 — 사주가 답합니다',
    price: 29900,
    badge: 'popular',
    thumbnailEmoji: '☯️',
    gradientFrom: '#F5D7E8',
    gradientTo: '#F5E8D7',
    is_active: true,
  },
  {
    id: '3',
    slug: 'tarot-today',
    category: 'tarot',
    title: '오늘의 타로 리딩',
    description: '오늘 하루를 위한 메시지, 지금 카드를 뽑아보세요',
    price: 4900,
    badge: 'new',
    thumbnailEmoji: '🃏',
    gradientFrom: '#E8D4F0',
    gradientTo: '#F5D7E8',
    is_active: true,
  },
  {
    id: '4',
    slug: 'astrology-natal',
    category: 'astrology',
    title: '별자리 출생 차트',
    description: '내가 어떤 사람으로 설계됐는지, 별이 알고 있습니다',
    price: 19900,
    thumbnailEmoji: '⭐',
    gradientFrom: '#4A3B5C',
    gradientTo: '#E8D4F0',
    is_active: true,
  },
  {
    id: '5',
    slug: 'mbti-compatibility',
    category: 'mbti',
    title: 'MBTI 궁합 분석',
    description: '우리가 자꾸 부딪히는 이유, 성격에 있었습니다',
    price: 14900,
    badge: 'new',
    thumbnailEmoji: '💕',
    gradientFrom: '#4A3B5C',
    gradientTo: '#F5D7E8',
    is_active: true,
  },
  {
    id: '6',
    slug: 'saju-yearly',
    category: 'saju',
    title: '신년 운세 사주',
    description: '올해 언제가 내 인생의 터닝포인트일까요',
    price: 39900,
    badge: 'popular',
    thumbnailEmoji: '🔮',
    gradientFrom: '#F5D7E8',
    gradientTo: '#E8D4F0',
    is_active: true,
  },
  {
    id: '7',
    slug: 'tarot-love',
    category: 'tarot',
    title: '연애 타로 리딩',
    description: '그 사람 마음, 타로 카드가 솔직하게 말해줍니다',
    price: 9900,
    thumbnailEmoji: '♥️',
    gradientFrom: '#E8D4F0',
    gradientTo: '#F5D7E8',
    is_active: true,
  },
  {
    id: '8',
    slug: 'astrology-compatibility',
    category: 'astrology',
    title: '별자리 궁합',
    description: '이 관계, 우주가 설계한 건지 — 별자리가 증명합니다',
    price: 14900,
    thumbnailEmoji: '🌟',
    gradientFrom: '#4A3B5C',
    gradientTo: '#E8D4F0',
    is_active: true,
  },
];
