import { Content } from '@/types/content';

// TODO: [백엔드 연동] 더미데이터를 /api/contents 실제 호출로 교체
export const DUMMY_CONTENTS: Content[] = [
  {
    id: '1',
    slug: 'mbti-basic',
    category: 'mbti',
    title: 'MBTI 기본 유형 해석',
    description: '나의 MBTI 유형이 가진 깊은 심리적 특성을 AI가 분석합니다.',
    price: 9900,
    badge: 'popular',
    thumbnailEmoji: '🧠',
    gradientFrom: '#4A3B5C',
    gradientTo: '#F5D7E8',
  },
  {
    id: '2',
    slug: 'saju-deep',
    category: 'saju',
    title: '심층 사주 분석',
    description: '생년월일시로 읽는 나만의 사주팔자 — AI 심층 분석 보고서.',
    price: 29900,
    badge: 'popular',
    thumbnailEmoji: '☯️',
    gradientFrom: '#F5D7E8',
    gradientTo: '#F5E8D7',
  },
  {
    id: '3',
    slug: 'tarot-today',
    category: 'tarot',
    title: '오늘의 타로 리딩',
    description: '지금 이 순간, 타로 카드가 전하는 메시지를 확인하세요.',
    price: 4900,
    badge: 'new',
    thumbnailEmoji: '🃏',
    gradientFrom: '#E8D4F0',
    gradientTo: '#F5D7E8',
  },
  {
    id: '4',
    slug: 'astrology-natal',
    category: 'astrology',
    title: '별자리 출생 차트',
    description: '태어난 순간의 별자리 배치로 읽는 나의 운명 지도.',
    price: 19900,
    thumbnailEmoji: '⭐',
    gradientFrom: '#4A3B5C',
    gradientTo: '#E8D4F0',
  },
  {
    id: '5',
    slug: 'mbti-compatibility',
    category: 'mbti',
    title: 'MBTI 궁합 분석',
    description: '두 유형의 관계 역학과 갈등 해소 방법을 AI가 분석합니다.',
    price: 14900,
    badge: 'new',
    thumbnailEmoji: '💕',
    gradientFrom: '#4A3B5C',
    gradientTo: '#F5D7E8',
  },
  {
    id: '6',
    slug: 'saju-yearly',
    category: 'saju',
    title: '신년 운세 사주',
    description: '올해 나에게 찾아오는 운의 흐름 — 월별 상세 분석 포함.',
    price: 39900,
    badge: 'popular',
    thumbnailEmoji: '🔮',
    gradientFrom: '#F5D7E8',
    gradientTo: '#E8D4F0',
  },
  {
    id: '7',
    slug: 'tarot-love',
    category: 'tarot',
    title: '연애 타로 리딩',
    description: '지금 나의 연애 운과 상대의 마음을 타로로 읽어드립니다.',
    price: 9900,
    thumbnailEmoji: '♥️',
    gradientFrom: '#E8D4F0',
    gradientTo: '#F5D7E8',
  },
  {
    id: '8',
    slug: 'astrology-compatibility',
    category: 'astrology',
    title: '별자리 궁합',
    description: '두 별자리의 천체적 연결을 분석해 관계의 가능성을 봅니다.',
    price: 14900,
    thumbnailEmoji: '🌟',
    gradientFrom: '#4A3B5C',
    gradientTo: '#E8D4F0',
  },
];
